const [appModule,firestoreModule]=await Promise.all([
  import(`https://www.gstatic.com/firebasejs/10.12.5/firebase-app.js`),
  import(`https://www.gstatic.com/firebasejs/10.12.5/firebase-firestore.js`)
]);
const {initializeApp,getApps,getApp}=appModule;
const {getFirestore,collection,getDocs,doc,getDoc,setDoc,deleteDoc,serverTimestamp}=firestoreModule;
const firebaseConfig={apiKey:`AIzaSyDmkPioDg5ZewsX2ANM1hAqgVWyzLeezeU`,authDomain:`mobilehub-4eb1d.firebaseapp.com`,projectId:`mobilehub-4eb1d`,storageBucket:`mobilehub-4eb1d.firebasestorage.app`,messagingSenderId:`13420871425`,appId:`1:13420871425:web:e253fe9c5aebbc5925a500`,measurementId:`G-RYWYCQXBT8`};
const firebaseApp=getApps().length?getApp():initializeApp(firebaseConfig);const db=getFirestore(firebaseApp);
const COLLECTION=`orangeExcelAssessments`;
const CONFIG_COLLECTION=`orangeExcelConfig`;
const CONFIG_DOC=`site`;
const SESSION=`coderzOrangeAdminSession`;
const PIN_HASH=`9060ce5653093cd9bff480cb01ff0e3a790e6f545e214a3dd85841daabac7848`;
const FILES={
  d1f1:{day:1,title:`Advanced Formulas & Logical Functions`,sub:`Customer Care / Operations`,download:`../../downloads/day1/01_Advanced_Formulas_Logical_Functions_CODERZ_DAY1_CUSTOMER_CARE_FINAL.xlsx`},
  d1f2:{day:1,title:`XLOOKUP & Dynamic Arrays`,sub:`HR`,download:`../../downloads/day1/02_XLOOKUP_Dynamic_Arrays_CODERZ_DAY1_HR_FINAL.xlsx`},
  d1f3:{day:1,title:`Advanced Text & Date Functions`,sub:`Cross-Department`,download:`../../downloads/day1/03_Advanced_Text_Date_Functions_CODERZ_DAY1_FINAL.xlsx`},
  d1f4:{day:1,title:`Day 1 Integrated Assignment`,sub:`Team Practice`,download:`../../downloads/day1/04_Day1_Integrated_Assignment_CODERZ.xlsx`},
  d2f1:{day:2,title:`PivotTable — 20-Second Report`,sub:`Commercial / Management`,download:`../../downloads/day2/05_Pivot_Table_CODERZ_TRAINER_STYLE.xlsx`},
  d2f2:{day:2,title:`Power Query Data Factory`,sub:`Cross-Department`,download:`../../downloads/day2/06_Power_Query_Data_Factory_CODERZ_DAY_2.xlsx`},
  d2f3:{day:2,title:`Power Query Source Pack`,sub:`ZIP Source Files`,download:`../../downloads/day2/DAY2_Power_Query_Source_Pack.zip`},
  d2f4:{day:2,title:`Network Alert Engine`,sub:`Network / Technical Operations`,download:`../../downloads/day2/07_Conditional_Formatting_Alert_Engine_CODERZ_DAY_2_NETWORK_FINAL.xlsx`},
  d2f5:{day:2,title:`Day 2 Final Challenge`,sub:`Integrated Practice`,download:null},
  d3f1:{day:3,title:`Interactive Dashboard`,sub:`Commercial / Management`,download:`../../downloads/day3/09_Interactive_Dashboard_CODERZ_DAY_3_EASY.xlsx`},
  d3f2:{day:3,title:`Macros + Protection`,sub:`Finance / Back Office`,download:`../../downloads/day3/10_Macros_Automation_Protection_CODERZ_DAY_3_FINANCE_FINAL.xlsx`},
  d3f3:{day:3,title:`Final Executive Dashboard Challenge`,sub:`Final Course Challenge`,download:`../../downloads/day3/11_Final_Executive_Dashboard_Challenge_CODERZ_DAY_3_EASY.xlsx`}
};
const DAY_INFO={1:{title:`Day 1`,sub:`Formulas • XLOOKUP • Text & Dates`},2:{title:`Day 2`,sub:`PivotTables • Power Query • Alerts`},3:{title:`Day 3`,sub:`Dashboards • Automation • Final Challenge`}};
const DEFAULT_FILES=Object.fromEntries(Object.keys(FILES).map((id)=>[id,false]));
const DEFAULT_LIVE={currentFile:``,pulse:{enabled:false,id:``,question:`كيف الوضع؟`,options:[{value:`good`,label:`تمام 👍`},{value:`repeat`,label:`بدنا إعادة نقطة`},{value:`faster`,label:`ممكن أسرع شوي`}]},breakMode:{enabled:false,returnTime:``}};
const DEFAULT_CONFIG={siteLive:true,introVisible:true,resetNonce:``,announcementEnabled:false,announcementText:``,assessmentEnabled:true,assessmentPhase:`pre`,attendanceEnabled:false,attendanceDay:0,dayVisibility:{day1:false,day2:false,day3:false},files:DEFAULT_FILES,customFiles:[],liveExperience:DEFAULT_LIVE};
let config={...DEFAULT_CONFIG,dayVisibility:{...DEFAULT_CONFIG.dayVisibility},files:{...DEFAULT_FILES}};
let attempts=[];
let attendance=[];
let liveQuestions=[];
let pulseResponses=[];
let livePresence=[];
const $=(id)=>document.getElementById(id);
const norm=(raw={})=>({...DEFAULT_CONFIG,...raw,dayVisibility:{...DEFAULT_CONFIG.dayVisibility,...(raw.dayVisibility||{})},files:{...DEFAULT_FILES,...(raw.files||{})},customFiles:Array.isArray(raw.customFiles)?raw.customFiles:[],liveExperience:{...DEFAULT_LIVE,...(raw.liveExperience||{}),pulse:{...DEFAULT_LIVE.pulse,...(raw.liveExperience?.pulse||{})},breakMode:{...DEFAULT_LIVE.breakMode,...(raw.liveExperience?.breakMode||{})}}});
const toast=(text)=>{if(!$(`toast`))return;$(`toast`).textContent=text;$(`toast`).classList.add(`show`);clearTimeout(window.__toast);window.__toast=setTimeout(()=>$(`toast`).classList.remove(`show`),1800)};
const hash=async(text)=>{const buffer=await crypto.subtle.digest(`SHA-256`,new TextEncoder().encode(text));return Array.from(new Uint8Array(buffer)).map((b)=>b.toString(16).padStart(2,`0`)).join(``)};
const save=async(patch,message=`تم الحفظ`)=>{config=norm({...config,...patch});await setDoc(doc(db,CONFIG_COLLECTION,CONFIG_DOC),{...patch,updatedAt:serverTimestamp()},{merge:true});renderAll();toast(message)};
const loadConfig=async()=>{const snap=await getDoc(doc(db,CONFIG_COLLECTION,CONFIG_DOC));config=norm(snap.exists()?snap.data():{});if(!snap.exists())await setDoc(doc(db,CONFIG_COLLECTION,CONFIG_DOC),config)};
const countOpenDays=()=>Object.values(config.dayVisibility).filter(Boolean).length;
const countOpenFiles=()=>Object.values(config.files).filter(Boolean).length+(config.customFiles||[]).filter((f)=>f.enabled).length;
const esc=(v)=>String(v??``).replace(/[&<>"']/g,(ch)=>({[`&`]:`&amp;`,[`<`]:`&lt;`,[`>`]:`&gt;`,[`"`]:`&quot;`,[`'`]:`&#39;`}[ch]));
const getCustomFile=(id)=>config.customFiles?.find((f)=>f.id===id)||null;
const getFileMeta=(id)=>FILES[id]||getCustomFile(id);
const customDownload=(f,fromAdmin=true)=>`${fromAdmin?`../../`:`../`}downloads/day${f.day}/${encodeURIComponent(f.fileName)}`;
const renderStatus=()=>{if($(`statusDays`))$(`statusDays`).textContent=`${countOpenDays()} Days Open`;if($(`statusFiles`))$(`statusFiles`).textContent=`${countOpenFiles()} Files Open`;if($(`statusAssessment`))$(`statusAssessment`).textContent=config.assessmentEnabled?config.assessmentPhase.toUpperCase():`CLOSED`;if($(`statusAttendance`))$(`statusAttendance`).textContent=config.attendanceEnabled?`Attendance D${config.attendanceDay}`:`Attendance OFF`};
const toggleDay=async(day,open)=>{const dayVisibility=open?{day1:false,day2:false,day3:false}:{...config.dayVisibility};dayVisibility[`day${day}`]=open;const current=config.liveExperience||DEFAULT_LIVE;const currentFile=open&&getFileMeta(current.currentFile)?.day!==day?``:current.currentFile||``;await save({dayVisibility,liveExperience:{...current,currentFile}},open?`${DAY_INFO[day].title} هو اليوم الظاهر للمتدربين`:`${DAY_INFO[day].title} مخفي`)};
const toggleFile=async(id,open)=>{const files={...config.files,[id]:open};const current=config.liveExperience||DEFAULT_LIVE;const liveExperience=!open&&current.currentFile===id?{...current,currentFile:``}:current;await save({files,liveExperience},open?`تم إظهار الملف`:`تم إخفاء الملف`)};
const toggleCustomFile=async(id,open)=>{const customFiles=(config.customFiles||[]).map((f)=>f.id===id?{...f,enabled:open}:f);const current=config.liveExperience||DEFAULT_LIVE;const liveExperience=!open&&current.currentFile===id?{...current,currentFile:``}:current;await save({customFiles,liveExperience},open?`تم إظهار الملف الإضافي`:`تم إخفاء الملف الإضافي`)};
const addCustomFile=async()=>{const day=Number($(`newFileDay`)?.value||0);const title=$(`newFileTitle`)?.value.trim()||``;const sub=$(`newFileSub`)?.value.trim()||`Additional Material`;const fileName=$(`newFileName`)?.value.trim()||``;if(![1,2,3].includes(day)){toast(`اختر اليوم`);return}if(!title){toast(`اكتب الاسم الظاهر للملف`);return}if(!fileName){toast(`اكتب اسم الملف كما رفعته على GitHub`);return}if(/[\\/]/.test(fileName)||fileName.startsWith(`.`)||fileName.includes(`..`)){toast(`اسم الملف غير صالح — استخدم اسم الملف فقط بدون مسار`);return}const duplicate=(config.customFiles||[]).some((f)=>f.day===day&&f.fileName.toLowerCase()===fileName.toLowerCase());if(duplicate){toast(`هذا الملف مضاف مسبقاً لهذا اليوم`);return}const id=`cx_${day}_${Date.now().toString(36)}`;const customFiles=[...(config.customFiles||[]),{id,day,title,sub,fileName,enabled:false}];await save({customFiles},`تمت إضافة الملف — فعّل Toggle عندما تريد إظهاره`);$(`newFileTitle`).value=``;$(`newFileSub`).value=``;$(`newFileName`).value=``};
const deleteCustomFile=async(id)=>{const file=getCustomFile(id);if(!file)return;if(!confirm(`حذف ${file.title} من قائمة الموقع؟\nلن يتم حذف الملف نفسه من GitHub.`))return;const customFiles=(config.customFiles||[]).filter((f)=>f.id!==id);const current=config.liveExperience||DEFAULT_LIVE;const liveExperience=current.currentFile===id?{...current,currentFile:``}:current;await save({customFiles,liveExperience},`تم حذف تعريف الملف من الموقع`)};
const renderDays=()=>{const box=$(`dayCards`);if(!box)return;box.innerHTML=``;[1,2,3].forEach((day)=>{const open=!!config.dayVisibility[`day${day}`];const card=document.createElement(`article`);card.className=`day-card${open?` open`:``}`;const staticRows=Object.entries(FILES).filter(([,f])=>f.day===day).map(([id,f])=>{const downloadControl=f.download?`<a class="file-download" href="${f.download}" download title="Download" aria-label="Download ${esc(f.title)}"><i data-lucide="download" size="15"></i></a>`:`<span class="file-download disabled" title="Download file is not included in this package" aria-label="Download unavailable"><i data-lucide="download" size="15"></i></span>`;return `<div class="file-row"><div class="file-copy"><b>${esc(f.title)}</b><small>${esc(f.sub)}</small></div><div class="file-controls">${downloadControl}<label class="switch"><input type="checkbox" data-file="${id}" ${config.files[id]?`checked`:``}><span class="slider"></span></label></div></div>`}).join(``);const customRows=(config.customFiles||[]).filter((f)=>f.day===day).map((f)=>`<div class="file-row"><div class="file-copy"><b>${esc(f.title)} <span style="font-size:8px;color:var(--orange)">ADDED</span></b><small>${esc(f.sub)} • ${esc(f.fileName)}</small></div><div class="file-controls"><a class="file-download" href="${customDownload(f,true)}" download title="Download"><i data-lucide="download" size="15"></i></a><button class="file-download" data-custom-delete="${f.id}" type="button" title="Remove from site" style="color:var(--red)"><i data-lucide="trash-2" size="14"></i></button><label class="switch"><input type="checkbox" data-custom-file="${f.id}" ${f.enabled?`checked`:``}><span class="slider"></span></label></div></div>`).join(``);card.innerHTML=`<div class="day-head"><div><h2>${DAY_INFO[day].title}</h2><p>${DAY_INFO[day].sub}</p></div><label class="switch"><input type="checkbox" data-day="${day}" ${open?`checked`:``}><span class="slider"></span></label></div><a class="day-link" href="../../day-${day}/" target="_blank"><span>فتح رابط ${DAY_INFO[day].title}</span><i data-lucide="external-link" size="13"></i></a><div class="files">${staticRows}${customRows}</div>`;box.appendChild(card)});box.querySelectorAll(`[data-day]`).forEach((input)=>input.addEventListener(`change`,()=>toggleDay(Number(input.dataset.day),input.checked)));box.querySelectorAll(`[data-file]`).forEach((input)=>input.addEventListener(`change`,()=>toggleFile(input.dataset.file,input.checked)));box.querySelectorAll(`[data-custom-file]`).forEach((input)=>input.addEventListener(`change`,()=>toggleCustomFile(input.dataset.customFile,input.checked)));box.querySelectorAll(`[data-custom-delete]`).forEach((button)=>button.addEventListener(`click`,()=>deleteCustomFile(button.dataset.customDelete)));lucide.createIcons()};
const setAssessment=async(mode)=>save({assessmentPhase:mode,assessmentEnabled:mode!==`closed`},mode===`pre`?`PRE مفتوح`:mode===`post`?`POST مفتوح`:`التقييم مغلق`);
const renderAssessment=()=>{const phase=config.assessmentEnabled?config.assessmentPhase:`closed`;document.querySelectorAll(`[data-assess]`).forEach((b)=>b.classList.toggle(`active`,b.dataset.assess===phase))};
const setAttendance=async(day)=>{await save({attendanceEnabled:true,attendanceDay:day},`تم فتح حضور Day ${day}`);await loadAttendance()};
const closeAttendance=async()=>{await save({attendanceEnabled:false,attendanceDay:0},`تم إغلاق الحضور`)};
const renderAttendanceMode=()=>{document.querySelectorAll(`[data-att]`).forEach((b)=>b.classList.toggle(`active`,config.attendanceEnabled&&Number(b.dataset.att)===Number(config.attendanceDay)))};
const loadAttendance=async()=>{try{const snap=await getDocs(collection(db,CONFIG_COLLECTION));attendance=snap.docs.map((d)=>({id:d.id,...d.data()})).filter((x)=>x.kind===`attendance`);renderAttendance()}catch(error){console.error(error);attendance=[];renderAttendance();toast(`تعذر قراءة سجل الحضور`)} };
const renderAttendance=()=>{const counts={1:0,2:0,3:0};attendance.forEach((a)=>{if(counts[a.day]!==undefined)counts[a.day]++});if($(`aDay1`))$(`aDay1`).textContent=counts[1];if($(`aDay2`))$(`aDay2`).textContent=counts[2];if($(`aDay3`))$(`aDay3`).textContent=counts[3];if($(`aUnique`))$(`aUnique`).textContent=new Set(attendance.map((a)=>(a.fullName||``).toLowerCase())).size;if($(`attendanceBody`)){$(`attendanceBody`).innerHTML=attendance.sort((a,b)=>Number(a.day)-Number(b.day)||(a.fullName||``).localeCompare(b.fullName||``, `ar`)).map((a)=>`<tr><td><b>${a.fullName||`—`}</b></td><td>${a.department||`—`}</td><td>Day ${a.day||`—`}</td><td><button class="btn danger small" data-att-delete="${a.id}">حذف</button></td></tr>`).join(``);document.querySelectorAll(`[data-att-delete]`).forEach((b)=>b.addEventListener(`click`,async()=>{if(!confirm(`حذف تسجيل الحضور؟`))return;await deleteDoc(doc(db,CONFIG_COLLECTION,b.dataset.attDelete));await loadAttendance();toast(`تم الحذف`)}))}};
const exportAttendance=()=>{const rows=[[`Participant`,`Department`,`Day`],...attendance.map((a)=>[a.fullName||``,a.department||``,a.day||``])];const csv=rows.map((r)=>r.map((v)=>`"${String(v).replaceAll(`"`,`""`)}"`).join(`,`)).join(`\n`);const blob=new Blob([`\uFEFF${csv}`],{type:`text/csv;charset=utf-8`});const a=document.createElement(`a`);a.href=URL.createObjectURL(blob);a.download=`orange-excel-attendance.csv`;a.click();URL.revokeObjectURL(a.href)};
const renderSite=()=>{if($(`announcementText`))$(`announcementText`).value=config.announcementText||``;if($(`announcementEnabled`))$(`announcementEnabled`).checked=!!config.announcementEnabled;if($(`introVisible`))$(`introVisible`).checked=config.introVisible!==false};
const getActiveCourseDay=()=>{const open=[1,2,3].find((day)=>config.dayVisibility?.[`day${day}`]);return open||0};
const fileOptions=(day)=>{const staticOptions=Object.entries(FILES).filter(([,f])=>!day||f.day===day).map(([id,f])=>`<option value="${id}">${esc(f.title)}</option>`);const customOptions=(config.customFiles||[]).filter((f)=>(!day||f.day===day)&&f.enabled).map((f)=>`<option value="${f.id}">${esc(f.title)} • Added</option>`);return [...staticOptions,...customOptions].join(``)};
const ensureBreakTimeOptions=()=>{if(!$(`breakHour`)||$(`breakHour`).dataset.ready)return;$(`breakHour`).innerHTML=Array.from({length:12},(_,i)=>`<option value="${i+1}">${String(i+1).padStart(2,`0`)}</option>`).join(``);$(`breakMinute`).innerHTML=Array.from({length:60},(_,i)=>`<option value="${i}">${String(i).padStart(2,`0`)}</option>`).join(``);$(`breakHour`).dataset.ready=`1`};
const setBreakPicker=(value)=>{ensureBreakTimeOptions();if(!$(`breakHour`))return;const [hRaw,mRaw]=String(value||``).split(`:`).map(Number);const valid=Number.isFinite(hRaw)&&Number.isFinite(mRaw);const h24=valid?hRaw:new Date().getHours();const m=valid?mRaw:new Date().getMinutes();const period=h24>=12?`PM`:`AM`;const h12=h24%12||12;$(`breakHour`).value=String(h12);$(`breakMinute`).value=String(m);$(`breakPeriod`).value=period};
const getBreakTime24=()=>{const h12=Number($(`breakHour`)?.value||12);const m=Number($(`breakMinute`)?.value||0);const period=$(`breakPeriod`)?.value||`AM`;const h24=(h12%12)+(period===`PM`?12:0);return `${String(h24).padStart(2,`0`)}:${String(m).padStart(2,`0`)}`};
const renderLiveControls=()=>{const l=config.liveExperience||DEFAULT_LIVE;const activeDay=getActiveCourseDay();if($(`liveAutoDay`))$(`liveAutoDay`).textContent=activeDay?`Day ${activeDay}`:`لا يوجد يوم مفتوح`;if($(`liveCurrentFile`)){const previous=l.currentFile||``;$(`liveCurrentFile`).innerHTML=`<option value="">بدون Highlight</option>${fileOptions(activeDay)}`;const meta=getFileMeta(previous);const valid=previous&&meta?.day===activeDay&&(!getCustomFile(previous)||getCustomFile(previous)?.enabled);$(`liveCurrentFile`).value=valid?previous:``}if($(`breakEnabled`))$(`breakEnabled`).checked=!!l.breakMode?.enabled;setBreakPicker(l.breakMode?.returnTime||``);if($(`pulseQuestion`))$(`pulseQuestion`).value=l.pulse?.question||`كيف الوضع؟`;const options=l.pulse?.options||DEFAULT_LIVE.pulse.options;options.slice(0,3).forEach((opt,i)=>{if($(`pulseOption${i+1}`))$(`pulseOption${i+1}`).value=opt.label||``})};
const saveCurrentFile=async()=>{const current=config.liveExperience||DEFAULT_LIVE;const activeDay=getActiveCourseDay();const selected=$(`liveCurrentFile`).value;const meta=getFileMeta(selected);const currentFile=selected&&meta?.day===activeDay&&(!getCustomFile(selected)||getCustomFile(selected)?.enabled)?selected:``;await save({liveExperience:{...current,currentFile}},currentFile?`تم تحديد الملف الحالي`:`تم إلغاء Highlight الملف`)};
const saveBreak=async(enabledOverride=null)=>{const current=config.liveExperience||DEFAULT_LIVE;const breakMode={enabled:enabledOverride===null?$(`breakEnabled`).checked:Boolean(enabledOverride),returnTime:getBreakTime24()};await save({liveExperience:{...current,breakMode}},breakMode.enabled?`Break Mode ON`:`تم إنهاء الاستراحة`)};
const sendPulse=async()=>{const current=config.liveExperience||DEFAULT_LIVE;const id=`pulse_${Date.now()}`;const defaults=DEFAULT_LIVE.pulse.options;const options=defaults.map((opt,i)=>({value:opt.value,label:$(`pulseOption${i+1}`)?.value.trim()||opt.label}));const pulse={enabled:true,id,question:$(`pulseQuestion`).value.trim()||`كيف الوضع؟`,options};await save({liveExperience:{...current,pulse}},`تم إرسال Pulse جديد`);pulseResponses=[];renderLiveData()};
const closePulse=async()=>{const current=config.liveExperience||DEFAULT_LIVE;await save({liveExperience:{...current,pulse:{...(current.pulse||DEFAULT_LIVE.pulse),enabled:false}}},`تم إغلاق Pulse`)};
const tsMillis=(v)=>v?.toMillis?.()||0;
const loadLiveData=async()=>{try{const [q,p,r]=await Promise.all([getDocs(collection(db,`orangeExcelQuestions`)),getDocs(collection(db,`orangeExcelPresence`)),getDocs(collection(db,`orangeExcelPulseResponses`))]);liveQuestions=q.docs.map(d=>({id:d.id,...d.data()})).sort((a,b)=>tsMillis(b.createdAt)-tsMillis(a.createdAt));livePresence=p.docs.map(d=>({id:d.id,...d.data()}));pulseResponses=r.docs.map(d=>({id:d.id,...d.data()}));renderLiveData()}catch(error){console.error(error);toast(`تعذر تحديث Live Dashboard`)}};
const renderLiveData=()=>{const now=Date.now();const online=livePresence.filter(x=>now-tsMillis(x.lastSeen)<120000);const pulseId=config.liveExperience?.pulse?.id||``;const currentPulse=pulseResponses.filter(x=>x.pulseId===pulseId);const options=config.liveExperience?.pulse?.options||DEFAULT_LIVE.pulse.options;const counts=Object.fromEntries(options.map((o)=>[o.value,0]));currentPulse.forEach(x=>{if(counts[x.answer]!==undefined)counts[x.answer]++});if($(`liveOnline`))$(`liveOnline`).textContent=online.length;if($(`liveOpenFiles`))$(`liveOpenFiles`).textContent=countOpenFiles();if($(`livePulseReplies`))$(`livePulseReplies`).textContent=currentPulse.length;if($(`liveQuestions`))$(`liveQuestions`).textContent=liveQuestions.length;if($(`pulseBreakdown`))$(`pulseBreakdown`).innerHTML=options.map((o)=>`${String(o.label||``).replace(/[<>]/g,``)}: <b>${counts[o.value]||0}</b>`).join(` &nbsp;•&nbsp; `);if($(`questionsList`))$(`questionsList`).innerHTML=liveQuestions.length?liveQuestions.slice(0,12).map(q=>`<div class="file-row"><div class="file-copy"><b>${String(q.text||``).replace(/[<>]/g,``)}</b><small>${q.page||`Participant`}</small></div><button class="btn danger small" data-question-delete="${q.id}">حذف</button></div>`).join(``):`<div class="sub">لا يوجد أسئلة بعد.</div>`;document.querySelectorAll(`[data-question-delete]`).forEach(b=>b.onclick=async()=>{await deleteDoc(doc(db,`orangeExcelQuestions`,b.dataset.questionDelete));await loadLiveData();toast(`تم حذف السؤال`)});if($(`roomSnapshot`)){const byPage=new Map();online.forEach(x=>byPage.set(x.page,(byPage.get(x.page)||0)+1));const rows=[...byPage.entries()].sort((a,b)=>b[1]-a[1]);$(`roomSnapshot`).innerHTML=rows.length?rows.map(([page,count])=>`<div class="file-row"><div class="file-copy"><b>${page||`/`}</b><small>Active in last 2 minutes</small></div><b>${count}</b></div>`).join(``):`<div class="sub">لا يوجد أجهزة نشطة حالياً.</div>`}};

const groupPeople=()=>{const map=new Map();attempts.forEach((a)=>{if(![`pre`,`post`].includes(a.mode))return;const key=(a.fullName||`Unknown`).trim().toLowerCase();if(!map.has(key))map.set(key,{name:a.fullName||`Unknown`,pre:null,post:null});const person=map.get(key);if(a.mode===`pre`)person.pre=a;if(a.mode===`post`)person.post=a});return [...map.values()].sort((a,b)=>a.name.localeCompare(b.name,`ar`))};
const avg=(arr)=>arr.length?(arr.reduce((s,v)=>s+v,0)/arr.length).toFixed(1):`—`;
const renderResults=()=>{const people=groupPeople();const term=($(`search`)?.value||``).trim().toLowerCase();const visible=people.filter((p)=>p.name.toLowerCase().includes(term));if($(`mPeople`))$(`mPeople`).textContent=people.length;if($(`mPre`))$(`mPre`).textContent=avg(people.filter((p)=>p.pre).map((p)=>Number(p.pre.score||0)));if($(`mPost`))$(`mPost`).textContent=avg(people.filter((p)=>p.post).map((p)=>Number(p.post.score||0)));if($(`mGain`))$(`mGain`).textContent=avg(people.filter((p)=>p.pre&&p.post).map((p)=>Number(p.post.score||0)-Number(p.pre.score||0)));if(!$(`resultsBody`))return;$(`resultsBody`).innerHTML=visible.map((p)=>{const pre=p.pre?Number(p.pre.score||0):null,post=p.post?Number(p.post.score||0):null,gain=pre!==null&&post!==null?post-pre:null;return `<tr><td><b>${p.name}</b></td><td>${pre===null?`—`:`${pre}/15`}</td><td>${post===null?`—`:`${post}/15`}</td><td>${gain===null?`—`:gain>0?`+${gain}`:gain}</td><td><div class="actions">${p.pre?`<button class="btn danger small" data-delete="${p.pre.id}">حذف PRE</button>`:``}${p.post?`<button class="btn danger small" data-delete="${p.post.id}">حذف POST</button>`:``}</div></td></tr>`}).join(``);document.querySelectorAll(`[data-delete]`).forEach((b)=>b.addEventListener(`click`,async()=>{if(!confirm(`حذف هذه النتيجة؟`))return;await deleteDoc(doc(db,COLLECTION,b.dataset.delete));await loadResults();toast(`تم الحذف`)}))};
const loadResults=async()=>{const snap=await getDocs(collection(db,COLLECTION));attempts=snap.docs.map((d)=>({id:d.id,...d.data()}));renderResults()};
const exportCSV=()=>{const people=groupPeople();const rows=[[`Participant`,`Pre`,`Post`,`Gain`],...people.map((p)=>{const pre=p.pre?Number(p.pre.score||0):``,post=p.post?Number(p.post.score||0):``;return [p.name,pre,post,pre!==``&&post!==``?post-pre:``]})];const csv=rows.map((r)=>r.map((v)=>`"${String(v).replaceAll(`"`,`""`)}"`).join(`,`)).join(`\n`);const blob=new Blob([`\uFEFF${csv}`],{type:`text/csv;charset=utf-8`});const a=document.createElement(`a`);a.href=URL.createObjectURL(blob);a.download=`orange-excel-results.csv`;a.click();URL.revokeObjectURL(a.href)};
const resetExperience=async()=>{const first=confirm(`RESET سيحذف كل بيانات تجارب الدورة الحالية من Firebase ويعيد الموقع لحالة البداية. متابعة؟`);if(!first)return;const typed=prompt(`للتأكيد النهائي اكتب RESET`);if(typed!==`RESET`){toast(`تم إلغاء RESET`);return}const collections=[COLLECTION,`orangeExcelQuestions`,`orangeExcelPresence`,`orangeExcelPulseResponses`,`orangeExcelAttendance`];try{for(const name of collections){const snap=await getDocs(collection(db,name));await Promise.all(snap.docs.map((d)=>deleteDoc(doc(db,name,d.id))))}const cfg=await getDocs(collection(db,CONFIG_COLLECTION));await Promise.all(cfg.docs.map((d)=>deleteDoc(doc(db,CONFIG_COLLECTION,d.id))));const fresh=norm({...DEFAULT_CONFIG,resetNonce:String(Date.now()),dayVisibility:{day1:false,day2:false,day3:false},files:{...DEFAULT_FILES},customFiles:[],liveExperience:{...DEFAULT_LIVE,pulse:{...DEFAULT_LIVE.pulse},breakMode:{...DEFAULT_LIVE.breakMode}}});await setDoc(doc(db,CONFIG_COLLECTION,CONFIG_DOC),fresh);config=fresh;attempts=[];attendance=[];liveQuestions=[];livePresence=[];pulseResponses=[];renderAll();renderResults();renderAttendance();toast(`تم RESET — الموقع جاهز لبداية جديدة`)}catch(error){console.error(error);toast(`تعذر تنفيذ RESET بالكامل`)} };
const renderAll=()=>{renderStatus();renderDays();renderAssessment();renderAttendanceMode();renderSite();renderLiveControls();renderLiveData()};
const showAdmin=async()=>{$(`loginView`).classList.add(`hidden`);$(`adminView`).classList.remove(`hidden`);await loadConfig();renderAll();await Promise.all([loadResults(),loadAttendance(),loadLiveData()]);lucide.createIcons()};
const login=async()=>{const value=$(`pin`).value.trim();if(await hash(value)!==PIN_HASH){$(`loginError`).textContent=`الرمز غير صحيح.`;return}sessionStorage.setItem(SESSION,`1`);await showAdmin()};
$(`loginBtn`)?.addEventListener(`click`,login);$(`pin`)?.addEventListener(`keydown`,(e)=>{if(e.key===`Enter`)login()});$(`logout`)?.addEventListener(`click`,()=>{sessionStorage.removeItem(SESSION);location.reload()});
document.querySelectorAll(`.tab`).forEach((b)=>b.addEventListener(`click`,()=>{document.querySelectorAll(`.tab`).forEach((x)=>x.classList.remove(`active`));document.querySelectorAll(`.panel`).forEach((x)=>x.classList.remove(`active`));b.classList.add(`active`);$(`panel-${b.dataset.tab}`)?.classList.add(`active`)}));
document.querySelectorAll(`[data-assess]`).forEach((b)=>b.addEventListener(`click`,()=>setAssessment(b.dataset.assess)));
document.querySelectorAll(`[data-att]`).forEach((b)=>b.addEventListener(`click`,()=>setAttendance(Number(b.dataset.att))));
$(`closeAttendance`)?.addEventListener(`click`,closeAttendance);$(`reloadAttendance`)?.addEventListener(`click`,loadAttendance);$(`exportAttendance`)?.addEventListener(`click`,exportAttendance);
$(`saveAnnouncement`)?.addEventListener(`click`,()=>save({announcementEnabled:$(`announcementEnabled`).checked,announcementText:$(`announcementText`).value.trim()},`تم حفظ الرسالة`));
$(`saveIntroVisibility`)?.addEventListener(`click`,()=>save({introVisible:$(`introVisible`).checked},$(`introVisible`).checked?`تم إظهار تعريف الدورة`:`تم إخفاء التعريف — الصفحة الآن مركزة على اليوم الجاري`));
$(`resetExperience`)?.addEventListener(`click`,resetExperience);
$(`hideAllDays`)?.addEventListener(`click`,()=>save({dayVisibility:{day1:false,day2:false,day3:false}},`تم إخفاء كل الأيام`));
$(`hideAllFiles`)?.addEventListener(`click`,()=>{const current=config.liveExperience||DEFAULT_LIVE;save({files:{...DEFAULT_FILES},customFiles:(config.customFiles||[]).map((f)=>({...f,enabled:false})),liveExperience:{...current,currentFile:``}},`تم إخفاء كل الملفات`)});
$(`search`)?.addEventListener(`input`,renderResults);$(`reloadResults`)?.addEventListener(`click`,loadResults);$(`export`)?.addEventListener(`click`,exportCSV);

$(`addCustomFile`)?.addEventListener(`click`,addCustomFile);
$(`saveCurrentFile`)?.addEventListener(`click`,saveCurrentFile);
$(`saveBreak`)?.addEventListener(`click`,()=>saveBreak());
$(`endBreak`)?.addEventListener(`click`,()=>saveBreak(false));
$(`sendPulse`)?.addEventListener(`click`,sendPulse);
$(`closePulse`)?.addEventListener(`click`,closePulse);
$(`reloadLiveData`)?.addEventListener(`click`,loadLiveData);
setInterval(()=>{if(sessionStorage.getItem(SESSION)===`1`)loadLiveData()},30000);
if(sessionStorage.getItem(SESSION)===`1`)showAdmin();
lucide.createIcons();